name: Demo Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    - uses: ./.github/workflow-templates/install-dotnet.yml
      with:
        version: 6.0.x