name: Demo Build

on:
  push:
    branches: [ master ]
    paths-include: [ "SampleLib/**", "SampleLib.Tests/**", ".github/workflows/ci.yml" ]
  pull_request:
    branches: [ master ]
    paths-include: [ "SampleLib/**", "SampleLib.Tests/**", ".github/workflows/ci.yml" ]
  workflow_dispatch:


jobs:
  build:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@master
    permissions:
      statuses: write
      checks: write
    with:
      name: Sample Lib
      install-workload: maui
      solution-path: SampleLib.sln
      run-tests: true
      code-sign: true
    secrets:
      codeSignKeyVault: ${{ secrets.CODESIGNKEYVAULT}}
      codeSignClientId: ${{ secrets.CODESIGNCLIENTID}}
      codeSignTenantId: ${{ secrets.CODESIGNTENANTID}}
      codeSignClientSecret: ${{ secrets.CODESIGNCLIENTSECRET}}
      codeSignCertificate: ${{ secrets.CODESIGNCERTIFICATE}}

  classicBuild:
    uses: ./.github/workflows/msbuild-build.yml
    with:
      name: XPlatLib
      solution-path: XPlatLib/XPlatLib.csproj
      artifact-name: XPlatLib-NuGet