name: Demo Build

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '*.md'
    - '.github/workflows/release.yml'
    - '.github/workflows/publish-release.yml'
    - 'build/*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/install-dotnet.yml
    secrets: inherit