on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    # secrets:
    #   envPAT:
    #     required: true
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Report Test Results
      uses: dorny/test-reporter@v1
      if: ${{ always() }}
      with:
        name: Sample Lib Test Results
        path: ./TestResults/*.trx
        reporter: dotnet-trx