name: Publish SampleLib Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget-from-release.yml@master
    secrets:
      apiKey: 'ThisKeyWillFail'
