name: Publish SampleLib Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    name: NuGet Publish
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ github.repository }}
          latest: true
          fileName: "*"
          out-file-path: "Artifacts/"
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "Root Directory:"
          ls

          cd Artifacts/
          echo "Artifacts Directory:"
          ls

        shell: bash