name: Publish SampleLib Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    name: NuGet Publish
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - uses: robinraju/release-downloader@main
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          fileName: "*"
          out-file-path: "Artifacts/"
          tarBall: false
          zipBall: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "GitHub Refs: ${{ github.ref }}"
          echo "Tag name: ${{ github.event.release.tag_name }}"
          echo "Assets url: ${{ github.event.release.assets_url }}"
          ls
        shell: bash