name: Publish SampleLib Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    name: NuGet Publish
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      # - uses: robinraju/release-downloader@main
      #   with:
      #     repository: ${{ github.repository }}
      #     latest: true
      #     fileName: "*"
      #     out-file-path: "Artifacts/"
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "GitHub Refs: ${{ github.ref }}"
          echo "Tag name: ${{ github.event.release.tag_name }}"
          echo "Assets url: ${{ github.event.release.assets_url }}"
        shell: bash