name: Start Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/install-dotnet.yml
    name: Build
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: [build]
    name: Release
    outputs:
      version-name: ${{ steps.process-version.outputs.version-name }}
      release-display-name: ${{ steps.process-version.outputs.release-display-name }}
      is-preview: ${{ steps.process-version.outputs.is-preview }}
    steps:
    - uses: actions/checkout@v2
      with:
        clean: true

    - uses: actions/download-artifact@v2
      with:
        name: NuGet
        version: latest
        path: Artifacts/

    - run: ./build/process-version.pl
      id: process-version
      name: Process Version

    - uses: dansiegel/action-automatic-releases@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ steps.process-version.outputs.version-name }}
        prerelease: ${{ steps.process-version.outputs.is-preview }}
        title: ${{ steps.process-version.outputs.release-display-name }}
        draft: true
        files: |
          Artifacts/*.nupkg
          Artifacts/*.snupkg