name: Start Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/install-dotnet.yml
    name: Build
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: [build]
    name: Release
    steps:
    - uses: actions/checkout@v2
      with:
        clean: true

    - uses: actions/download-artifact@v2
      with:
        name: NuGet
        version: latest
        path: Artifacts/

    - run: ./build/Process-Version.ps1
      name: Process Version
      shell: powershell

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ env.VersionName }}
        prerelease: ${{ env.IsPreview }}
        title: ${{ env.ReleaseDisplayName }}
        draft: true
        files: |
          Artifacts/*.nupkg
          Artifacts/*.snupkg