name: Start Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@master
    with:
      name: SampleLib
      install-workload: maui
      solution-path: SampleLib.sln
      run-tests: true
      code-sign: true
    secrets:
      codeSignKeyVault: ${{ secrets.CODESIGNKEYVAULT}}
      codeSignClientId: ${{ secrets.CODESIGNCLIENTID}}
      codeSignTenantId: ${{ secrets.CODESIGNTENANTID}}
      codeSignClientSecret: ${{ secrets.CODESIGNCLIENTSECRET}}
      codeSignCertificate: ${{ secrets.CODESIGNCERTIFICATE}}

  release:
    uses: avantipoint/workflow-templates/.github/workflows/generate-release.yml@master
    needs: [build]
    # permissions:
    #   contents: write
    with:
      package-name: SampleLib
